Update apply.yaml

diff --git a/.github/workflows/apply.yaml b/.github/workflows/apply.yaml
--- a/.github/workflows/apply.yaml
+++ b/.github/workflows/apply.yaml
@@ -10,13 +10,44 @@ env:
   CONFIG_DIRECTORY: "./"
   
 jobs:
+ create_pr:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Get latest Terraform run ID
+        id: get-run-id
+        run: |
+          # Set your Terraform Cloud organization and workspace
+          ORG_NAME="compan"
+          WORKSPACE_NAME="compan-workspace"
+          
+          # Fetch the workspace ID
+          WORKSPACE_ID=$(curl -s \
+            --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
+            https://app.terraform.io/api/v2/organizations/${ORG_NAME}/workspaces/${WORKSPACE_NAME} | jq -r '.data.id')
+          
+          echo "Workspace ID: $WORKSPACE_ID"
+          
+          if [ "$WORKSPACE_ID" == "null" ]; then
+            echo "Failed to fetch Workspace ID"
+            exit 1
+          fi
+          
+          # Fetch the latest run ID for the workspace
+          LATEST_RUN_ID=$(curl -s \
+            --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
+            https://app.terraform.io/api/v2/workspaces/${WORKSPACE_ID}/runs | jq -r '.data[0].id')
+          
+          echo "Latest Run ID: $LATEST_RUN_ID"
+    outputs:
+     LATEST_RUN_ID: ${{ steps.create_pr.outputs.LATEST_RUN_ID }}
  approval:
     runs-on: ubuntu-latest
+    env:
+      LATEST_RUN_ID: ${{ needs.create_pr.outputs.LATEST_RUN_ID }}
     steps:
       - name: Apply Terraform changes
         run: |
           # Assuming you have the latest run ID stored in a variable
-          LATEST_RUN_ID=run-HjVxFqxeDQfauSXy
           echo "Latest Run ID: $LATEST_RUN_ID"
       
           # Apply the Terraform changes using the Terraform Cloud API
