Update FINAL.yaml

diff --git a/.github/workflows/FINAL.yaml b/.github/workflows/FINAL.yaml
--- a/.github/workflows/FINAL.yaml
+++ b/.github/workflows/FINAL.yaml
@@ -244,7 +244,7 @@ jobs:
     runs-on: ubuntu-latest
     needs: check-if-rollback
     outputs:
-     LATEST_RUN_ID: ${{ steps.get-run-id.outputs.LATEST_RUN_ID }}
+      LATEST_RUN_ID: ${{ steps.get-run-id.outputs.LATEST_RUN_ID }}
 
     steps:
       - name: Checkout pre-release branch
@@ -267,7 +267,7 @@ jobs:
       - name: Create pull request
         run: gh pr create -B main -H pre-release --title 'Merge pre-release into main' --body 'Created by Github action'
         env:
-            GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
 
       - name: Wait 20 seconds
         run: sleep 20
@@ -300,7 +300,7 @@ jobs:
       - name: Merge pull request
         run: gh pr merge --merge --auto --subject 'Merge pre-release into main' --body 'Auto-merged by GitHub Action'
         env:
-            GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
 
       - name: Wait 20 seconds
         run: sleep 20
@@ -369,11 +369,10 @@ jobs:
           echo "::set-output name=plan_status::$PLAN_STATUS"
           # Set the LATEST_RUN_ID output for the next steps
           echo "LATEST_RUN_ID=$LATEST_RUN_ID" >> $GITHUB_OUTPUT
-      
+
       - name: Use latest plan status
         run: echo "The latest plan status is ${{ steps.get-run-id.outputs.plan_status }}"
-
-        
+       
   approval:
     needs: create-pull-request
     runs-on: ubuntu-latest
@@ -381,20 +380,29 @@ jobs:
     steps:
       - name: Apply Terraform changes
         run: |
+          set -e  # Exit immediately if a command exits with a non-zero status
+
           # Assuming you have the latest run ID stored in a variable
-          LATEST_RUN_ID="${{ needs.create_pr.outputs.LATEST_RUN_ID }}"
+          LATEST_RUN_ID="${{ needs.create-pull-request.outputs.LATEST_RUN_ID }}"
           echo "Latest Run ID: $LATEST_RUN_ID"
       
           # Apply the Terraform changes using the Terraform Cloud API
-          curl --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
-               --header "Content-Type: application/vnd.api+json" \
-               --request POST \
-               --data "{}" \
-               https://app.terraform.io/api/v2/runs/$LATEST_RUN_ID/actions/apply   
-      
+          apply_response=$(curl --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
+                                --header "Content-Type: application/vnd.api+json" \
+                                --request POST \
+                                --data '{}' \
+                                https://app.terraform.io/api/v2/runs/$LATEST_RUN_ID/actions/apply)
+          
+          echo "Apply Response: $apply_response"
+          
           # Extracting apply request ID from the response
           APPLY_REQUEST_ID=$(echo $apply_response | jq -r '.data.id')
           echo "Apply Request ID: $APPLY_REQUEST_ID"
+
+          if [[ -z "$APPLY_REQUEST_ID" ]]; then
+            echo "Error: APPLY_REQUEST_ID is empty"
+            exit 1
+          fi
 
           # Polling for the run status until it is completed
           while true; do
