Update Workflow_02.yaml

diff --git a/.github/workflows/Workflow_02.yaml b/.github/workflows/Workflow_02.yaml
--- a/.github/workflows/Workflow_02.yaml
+++ b/.github/workflows/Workflow_02.yaml
@@ -29,73 +29,164 @@ jobs:
             echo "Changes detected"
           fi
 
-      - name: create pull request
+      - name: Create pull request
         run: gh pr create -B main -H pre-release --title 'Merge pre-release into main' --body 'Created by Github action'
         env:
             GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
 
-      - name: Wait 20 seconds
-        run: sleep 20
+  check_and_merge_pr:
+    needs: create_pr
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout main branch
+        uses: actions/checkout@v3
+        with:
+          ref: main
+
+      - name: Check Terraform plan for PR
+        id: plan_pr
+        run: |
+          # Trigger a Terraform plan in Terraform Cloud using the API and check the result
+          PLAN_ID=$(curl --silent \
+            --header "Authorization: Bearer ${TFE_TOKEN}" \
+            --header "Content-Type: application/vnd.api+json" \
+            --data '{
+              "data": {
+                "attributes": {
+                  "is-destroy": false,
+                  "message": "Plan triggered by GitHub Actions"
+                },
+                "type": "runs",
+                "relationships": {
+                  "workspace": {
+                    "data": {
+                      "type": "workspaces",
+                      "id": "'${TFC_WORKSPACE}'"
+                    }
+                  }
+                }
+              }
+            }' https://app.terraform.io/api/v2/runs | jq -r '.data.id')
+
+          echo "Triggered plan with ID: ${PLAN_ID}"
+
+          # Poll the Terraform Cloud API for the plan status
+          while true; do
+            PLAN_STATUS=$(curl --silent \
+              --header "Authorization: Bearer ${TFE_TOKEN}" \
+              https://app.terraform.io/api/v2/runs/${PLAN_ID} | jq -r '.data.attributes.status')
+
+            if [[ "${PLAN_STATUS}" == "errored" ]]; then
+              echo "Terraform plan contains errors."
+              exit 1
+            elif [[ "${PLAN_STATUS}" == "planned_and_finished" ]]; then
+              echo "Terraform plan completed successfully."
+              break
+            else
+              echo "Waiting for Terraform plan to complete..."
+              sleep 20
+            fi
+          done
 
       - name: Merge pull request
+        if: steps.plan_pr.outcome == 'success'
         run: gh pr merge --merge --auto --subject 'Merge pre-release into main' --body 'Auto-merged by GitHub Action'
         env:
             GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
 
-      - name: Check latest Terraform plan
-        id: check_plan
+  post_merge_plan:
+    needs: check_and_merge_pr
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout main branch
+        uses: actions/checkout@v3
+        with:
+          ref: main
+
+      - name: Check Terraform plan after merge
+        id: plan_post_merge
         run: |
-          workspace_id="${{ secrets.TFC_WORKSPACE }}"
-          tfe_token="${{ secrets.TFE_TOKEN }}"
+          PLAN_ID=$(curl --silent \
+            --header "Authorization: Bearer ${TFE_TOKEN}" \
+            --header "Content-Type: application/vnd.api+json" \
+            --data '{
+              "data": {
+                "attributes": {
+                  "is-destroy": false,
+                  "message": "Plan triggered by GitHub Actions after merge"
+                },
+                "type": "runs",
+                "relationships": {
+                  "workspace": {
+                    "data": {
+                      "type": "workspaces",
+                      "id": "'${TFC_WORKSPACE}'"
+                    }
+                  }
+                }
+              }
+            }' https://app.terraform.io/api/v2/runs | jq -r '.data.id')
 
-          # Get the latest run ID for the workspace
-          latest_run_id=$(curl -s \
-            --header "Authorization: Bearer $tfe_token" \
-            "https://app.terraform.io/api/v2/runs?filter[workspace][id]=$workspace_id&page[size]=1" | jq -r '.data[0].id')
-
-          # Get the latest run details
-          plan_status=$(curl -s \
-            --header "Authorization: Bearer $tfe_token" \
-            "https://app.terraform.io/api/v2/runs/$latest_run_id" | jq -r '.data.attributes."status"')
-
-          # Check if the plan has changes
-          if [ "$plan_status" == "planned_and_finished" ]; then
-            has_changes=$(curl -s \
-              --header "Authorization: Bearer $tfe_token" \
-              "https://app.terraform.io/api/v2/runs/$latest_run_id/plan" | jq -r '.data.attributes."resource_changes" | length > 0')
-
-            if [ "$has_changes" == "true" ]; then
-              echo "Terraform plan has changes."
-              echo "::set-output name=skip_apply::false"
-            else
-              echo "Terraform plan has no changes."
-              echo "::set-output name=skip_apply::true"
-            fi
-          else
-            echo "Terraform plan status is not 'planned_and_finished'."
-            echo "::set-output name=skip_apply::false"
-          fi
-
-      - name: Wait for Terraform apply to complete
-        if: steps.check_plan.outputs.skip_apply == 'false'
-        id: wait_for_terraform
-        run: |
-          workspace_id="${{ secrets.TFC_WORKSPACE }}"
-          tfe_token="${{ secrets.TFE_TOKEN }}"
+          echo "Triggered plan with ID: ${PLAN_ID}"
 
           while true; do
-            run_status=$(curl -s \
-              --header "Authorization: Bearer $tfe_token" \
-              "https://app.terraform.io/api/v2/runs/$latest_run_id" | jq -r '.data.attributes."status"')
-            
-            if [ "$run_status" == "applied" ]; then
-              echo "Terraform apply completed."
-              break
-            elif [ "$run_status" == "errored" ]; then
-              echo "Terraform apply failed."
+            PLAN_STATUS=$(curl --silent \
+              --header "Authorization: Bearer ${TFE_TOKEN}" \
+              https://app.terraform.io/api/v2/runs/${PLAN_ID} | jq -r '.data.attributes.status')
+
+            if [[ "${PLAN_STATUS}" == "errored" ]]; then
+              echo "Terraform plan contains errors."
               exit 1
+            elif [[ "${PLAN_STATUS}" == "planned_and_finished" ]]; then
+              echo "Terraform plan completed successfully."
+              break
+            else
+              echo "Waiting for Terraform plan to complete..."
+              sleep 20
+            fi
+          done
+
+      - name: Apply Terraform changes
+        if: steps.plan_post_merge.outcome == 'success'
+        run: |
+          APPLY_ID=$(curl --silent \
+            --header "Authorization: Bearer ${TFE_TOKEN}" \
+            --header "Content-Type: application/vnd.api+json" \
+            --data '{
+              "data": {
+                "attributes": {
+                  "is-destroy": false,
+                  "message": "Apply triggered by GitHub Actions"
+                },
+                "type": "runs",
+                "relationships": {
+                  "workspace": {
+                    "data": {
+                      "type": "workspaces",
+                      "id": "'${TFC_WORKSPACE}'"
+                    }
+                  }
+                }
+              }
+            }' https://app.terraform.io/api/v2/runs | jq -r '.data.id')
+
+          echo "Triggered apply with ID: ${APPLY_ID}"
+
+          while true; do
+            APPLY_STATUS=$(curl --silent \
+              --header "Authorization: Bearer ${TFE_TOKEN}" \
+              https://app.terraform.io/api/v2/runs/${APPLY_ID} | jq -r '.data.attributes.status')
+
+            if [[ "${APPLY_STATUS}" == "errored" ]]; then
+              echo "Terraform apply contains errors."
+              exit 1
+            elif [[ "${APPLY_STATUS}" == "applied" ]]; then
+              echo "Terraform apply completed successfully."
+              break
             else
               echo "Waiting for Terraform apply to complete..."
-              sleep 30
+              sleep 20
             fi
           done
